In [1]:
faqs = """ What is the course fee for the AI & Deep Learning Bootcamp (ADLB 2025)? The course follows a monthly subscription model. You have to pay Rs 999 per month.

What is the total duration of the course? The program runs for 6 months. So, the total fee becomes approximately Rs 5994.

What topics are covered? You’ll study Python for AI, Math for Deep Learning, Neural Networks (including ANN, CNN, and RNN), Transfer Learning, Computer Vision, Natural Language Processing, TensorFlow, PyTorch, and also work on capstone projects.

Where can I check the detailed syllabus? You can view the complete syllabus here – https://learnwith.example.com/courses/adlb2025

Is a technical background required? No, the course is beginner-friendly and open to learners from all backgrounds.

What happens if I miss a live session? All sessions are recorded. You can watch the recordings later anytime.

How long is each live session? Approximately 2.5 hours.

Which language is used during the sessions? Hinglish — a mix of Hindi and English.

How will I know about upcoming classes? You will receive an email before each live session after you become a paid user.

Can I join the course in the middle? Yes, you can join anytime. Once you pay, all the past session recordings will be available on your dashboard.

Do I need to submit assignments? No, you don’t have to submit anything. You’ll get the solutions and can self-evaluate.

Are there any case studies or real projects? Yes, you’ll be doing practical projects and working on case studies.

Where can I contact the support team? You can email us at support.adlb@example.com

Where do I make the payments? All payments must be made on our official website – https://learnwith.example.com

Can I pay the full course fee at once? No, the program only accepts monthly payments.

What is the validity of a monthly payment? Your access is valid for 30 days from the date you make the payment.

What if I don’t like the course? You can request a refund within 7 days of your payment.

I’m outside India and unable to pay — what should I do? Please contact us at support.adlb@example.com and we’ll assist you.

Until when can I access the videos? As long as your subscription is active, you can watch all videos. If you complete all 6 payments, you’ll have access to the course content until December 2025.

Why is lifetime access not given? To keep the course affordable.

How can I ask doubts after sessions? A doubt form will be available in your dashboard. Fill it, and our team will arrange a one-on-one doubt-solving session.

Can I ask doubts from past sessions if I join late? Yes, just select "past week doubt" in the form.

What is required to get the certificate? You need to complete all 6 payments and attempt every course assessment.

I joined late. How can I pay for previous months? Once you pay for the current month, your dashboard will show payment links for earlier months.

Is placement assistance included? Yes, but not placement guarantee. Placement assistance includes portfolio building, resume reviews, soft skill sessions, mentorship talks, and job hunting strategies.

"""

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([faqs])

In [4]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'can': 4,
 'is': 5,
 'and': 6,
 'course': 7,
 'a': 8,
 'to': 9,
 'what': 10,
 'for': 11,
 'all': 12,
 'pay': 13,
 'will': 14,
 'your': 15,
 'on': 16,
 'session': 17,
 'sessions': 18,
 'payments': 19,
 'of': 20,
 'you’ll': 21,
 'example': 22,
 'com': 23,
 'if': 24,
 'how': 25,
 'yes': 26,
 'be': 27,
 'payment': 28,
 'access': 29,
 'fee': 30,
 'learning': 31,
 'adlb': 32,
 'monthly': 33,
 'have': 34,
 '6': 35,
 'months': 36,
 'are': 37,
 'projects': 38,
 'where': 39,
 'complete': 40,
 'no': 41,
 'from': 42,
 'live': 43,
 'join': 44,
 'in': 45,
 'once': 46,
 'past': 47,
 'dashboard': 48,
 'do': 49,
 'support': 50,
 'at': 51,
 'doubt': 52,
 'placement': 53,
 'ai': 54,
 'deep': 55,
 '2025': 56,
 'subscription': 57,
 'rs': 58,
 'month': 59,
 'total': 60,
 'program': 61,
 'approximately': 62,
 'language': 63,
 'syllabus': 64,
 '–': 65,
 'https': 66,
 'learnwith': 67,
 'required': 68,
 'watch': 69,
 'recordings': 70,
 'anytime': 71,
 'long': 72,
 'each': 73,
 '—

In [5]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])



In [6]:
input_sequences

[[10, 5],
 [10, 5, 1],
 [10, 5, 1, 7],
 [10, 5, 1, 7, 30],
 [10, 5, 1, 7, 30, 11],
 [10, 5, 1, 7, 30, 11, 1],
 [10, 5, 1, 7, 30, 11, 1, 54],
 [10, 5, 1, 7, 30, 11, 1, 54, 55],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7, 101],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7, 101, 8],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7, 101, 8, 33],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7, 101, 8, 33, 57],
 [10, 5, 1, 7, 30, 11, 1, 54, 55, 31, 100, 32, 56, 1, 7, 101, 8, 33, 57, 102],
 [10,
  5,
  1,
  7,
  30,
  11,
  1,
  54,
  55,
  31,
  100,
  32,
  56,
  1,
  7,
  101,
  8,
  33,
  57,
  102,
  2],
 [10,
  5,
  1,
  7,
  30,
  11,
  1,
  54,
  55,
  31

In [7]:
max_len = max([len(x) for x in input_sequences])
max_len

35

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [9]:
padded_sequences

array([[  0,   0,   0, ...,   0,  10,   5],
       [  0,   0,   0, ...,  10,   5,   1],
       [  0,   0,   0, ...,   5,   1,   7],
       ...,
       [  0,   0,   0, ..., 242,   6, 243],
       [  0,   0,   0, ...,   6, 243, 244],
       [  0,   0,   0, ..., 243, 244, 245]], dtype=int32)

In [10]:
X = padded_sequences[:,:-1]
y = padded_sequences[:,-1]

In [11]:
X

array([[  0,   0,   0, ...,   0,   0,  10],
       [  0,   0,   0, ...,   0,  10,   5],
       [  0,   0,   0, ...,  10,   5,   1],
       ...,
       [  0,   0,   0, ..., 241, 242,   6],
       [  0,   0,   0, ..., 242,   6, 243],
       [  0,   0,   0, ...,   6, 243, 244]], dtype=int32)

In [12]:
y

array([  5,   1,   7,  30,  11,   1,  54,  55,  31, 100,  32,  56,   1,
         7, 101,   8,  33,  57, 102,   2,  34,   9,  13,  58, 103, 104,
        59,   5,   1,  60, 105,  20,   1,   7,   1,  61, 106,  11,  35,
        36, 107,   1,  60,  30, 108,  62,  58, 109, 110,  37, 111,  21,
       112, 113,  11,  54, 114,  11,  55,  31, 115, 116, 117, 118, 119,
         6, 120, 121,  31, 122, 123, 124,  63, 125, 126, 127,   6, 128,
       129,  16, 130,  38,   4,   3, 131,   1, 132,  64,   2,   4, 133,
         1,  40,  64, 134,  65,  66,  67,  22,  23, 135, 136,   8, 137,
       138,  68,  41,   1,   7,   5, 139, 140,   6, 141,   9, 142,  42,
        12, 143, 144,  24,   3, 145,   8,  43,  17,  12,  18,  37, 146,
         2,   4,  69,   1,  70, 147,  71,  72,   5,  73,  43,  17,  62,
       148, 149, 150,  63,   5, 152, 153,   1,  18, 154,  74,   8, 155,
        20, 156,   6, 157,  14,   3, 158, 159, 160, 161,   2,  14, 162,
       163,  75, 164,  73,  43,  17,  76,   2, 165,   8, 166, 16

In [13]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=283)

In [14]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [16]:
model = Sequential()
model.add(Embedding(283, 100, input_length=56))
model.add(LSTM(150))
model.add(Dense(283, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.fit(X,y,epochs=100)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - accuracy: 0.0366 - loss: 5.6351
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.0682 - loss: 5.2969
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.0532 - loss: 5.1422
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.0674 - loss: 5.0442
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - accuracy: 0.0618 - loss: 5.0324
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.0689 - loss: 4.8987
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.0899 - loss: 4.8595
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.0798 - loss: 4.8407
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 108ms/step - accuracy: 0.0793 - loss: 4.8300
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - accuracy: 0.0862 - loss: 4.7067
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.0677 - loss: 4.6537
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/ste

In [21]:
from sys import ps1
text = 'What topics'

for i in range(10):
  token_text = tokenizer.texts_to_sequences([text])[0]
  padded_text = pad_sequences([token_text],maxlen=56,padding='pre')

  pos = np.argmax(model.predict(padded_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)





1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
What topics are
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
What topics are covered
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
What topics are covered you’ll
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
What topics are covered you’ll study
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
What topics are covered you’ll study python
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
What topics are covered you’ll study python for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
What topics are covered you’ll study python for ai
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
What topics are covered you’ll study python for ai math
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
What topics are covered you’ll study python for ai math for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
What topics are covered you’ll study python for ai math for deep
